# @package _global_

# specify here default training configuration
defaults:
    - trainer: default_trainer.yaml
    - model: model.yaml
    - datamodule: datamodule.yaml
    - seeds: default_seeds.yaml # set this to null if you don't want to use seeds
    - callbacks: default_callbacks.yaml # set this to null if you don't want to use callbacks
    - logger: null # set logger here or use command line (e.g. `python train.py logger=wandb`)

    # we add this just to enable color logging
    # - hydra/hydra_logging: colorlog
    # - hydra/job_logging: colorlog

# path to folder with data
data_dir: data/
log_dir: logs/${now:%Y-%m-%d}
